Verify Parquet Structure

In [1]:
import pandas as pd

In [2]:
caiso = pd.read_parquet("Datasets/CAISO/caiso_with_residuals.parquet")

In [3]:
caiso

,HR,PGE,SCE,SDGE,VEA,CAISO,seconds,day_index_3am,time,residuals,fitted,y
0,0,9844.620265,9928.001620,2088.453772,92.069996,21953.146163,1546300800,0,2018-12-31 17:00:00-07:00,0.000000,0.000000,0.000000
1,1,9507.691745,9604.449654,1998.915397,92.659879,21203.716174,1546304400,0,2018-12-31 18:00:00-07:00,0.000000,0.000000,0.000000
2,2,9251.837855,9340.780790,1934.057172,93.592896,20620.268525,1546308000,0,2018-12-31 19:00:00-07:00,0.000000,0.000000,0.000000
3,3,9123.916881,9183.897175,1891.808751,97.052299,20296.675172,1546311600,0,2018-12-31 20:00:00-07:00,0.000000,0.000000,0.000000
4,4,9156.274437,9170.727964,1898.794915,101.469059,20327.266153,1546315200,1,2018-12-31 21:00:00-07:00,0.511937,0.000083,0.512021
...,...,...,...,...,...,...,...,...,...,...,...,...
56946,19,16282.880880,16406.503620,2982.160214,121.460361,35793.005193,1751331600,2373,2025-06-30 13:00:00-06:00,-0.014508,1.633906,1.619398
56947,20,15913.359630,15813.555210,2934.673798,110.556472,34772.145278,1751335200,2373,2025-06-30 14:00:00-06:00,0.002201,1.489926,1.492127
56948,21,15324.313130,15213.739570,2853.128183,98.707809,33489.888495,1751338800,2373,2025-06-30 15:00:00-06:00,0.057379,1.274887,1.332267
56949,22,14194.494270,14301.485070,2710.082027,86.417304,31292.478469,1751342400,2373,2025-06-30 16:00:00-06:00,0.018423,1.039891,1.058314
56950,23,13084.309810,13028.386380,2592.019210,76.366296,28781.081669,1751346000,2373,2025-06-30 17:00:00-06:00,-0.076952,0.822169,0.745217

In [4]:
caiso_MW = caiso['CAISO']/1000

In [5]:
caiso_beast = pd.concat([caiso['time'], caiso['CAISO']], axis=1)

In [6]:
caiso_beast

                           time         CAISO
0     2018-12-31 17:00:00-07:00  21953.146163
1     2018-12-31 18:00:00-07:00  21203.716174
2     2018-12-31 19:00:00-07:00  20620.268525
3     2018-12-31 20:00:00-07:00  20296.675172
4     2018-12-31 21:00:00-07:00  20327.266153
...                         ...           ...
56946 2025-06-30 13:00:00-06:00  35793.005193
56947 2025-06-30 14:00:00-06:00  34772.145278
56948 2025-06-30 15:00:00-06:00  33489.888495
56949 2025-06-30 16:00:00-06:00  31292.478469
56950 2025-06-30 17:00:00-06:00  28781.081669

[56951 rows x 2 columns]

In [7]:
caiso_beast.to_csv("CAISO_MW.csv")

In [8]:
caiso_beast = caiso_beast.rename(columns={'time':'start_time', 'CAISO' : 'tensor'})

In [9]:
import pickle
import zipfile
import pgzip
import os

In [10]:
path = os.getcwd()

In [11]:
path

'/home/lambpc/AMARANTH/opensourcegridmodeling/Transformer/code/code'

In [12]:
with pgzip.open(os.path.join(path,'Datasets/PJM_energy_datasets/dayton_dict.pkl.pgz')) as f:
            sd = pickle.load(f)

In [13]:
sd

{'start_time': datetime.datetime(2004, 10, 1, 0, 0, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=68400))),
 'tensor': tensor([1621., 1536., 1500.,  ..., 2405., 2250., 2042.])}

In [14]:
len(sd['tensor'])

121296

In [15]:
import torch
torch.stack([sd['tensor']]).unsqueeze(-1)

tensor([[[1621.],
         [1536.],
         [1500.],
         ...,
         [2405.],
         [2250.],
         [2042.]]])

In [16]:
pd.DataFrame(sd)

                      start_time  tensor
0      2004-10-01 00:00:00-05:00  1621.0
1      2004-10-01 00:00:00-05:00  1536.0
2      2004-10-01 00:00:00-05:00  1500.0
3      2004-10-01 00:00:00-05:00  1434.0
4      2004-10-01 00:00:00-05:00  1489.0
...                          ...     ...
121291 2004-10-01 00:00:00-05:00  2554.0
121292 2004-10-01 00:00:00-05:00  2481.0
121293 2004-10-01 00:00:00-05:00  2405.0
121294 2004-10-01 00:00:00-05:00  2250.0
121295 2004-10-01 00:00:00-05:00  2042.0

[121296 rows x 2 columns]

In [17]:
time_needed = sd['start_time']

In [18]:
import datetime
tensor = torch.from_numpy(caiso_beast['tensor'].values)

In [19]:
dict = {'start_time' : datetime.datetime(2018,12,31,0,0, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200))), 'tensor' : tensor}

In [20]:
len(dict['tensor'])

56951

In [21]:
with open('/home/lambpc/AMARANTH/opensourcegridmodeling/Transformer/code/code/Datasets/CAISO/caiso_dict.pkl','wb') as f :
    pickle.dump(dict,f)

In [22]:
with open(os.path.join(path,'Datasets/CAISO/caiso_dict.pkl'),'rb') as f :
    sd = pickle.load(f)

In [23]:
with pgzip.open(os.path.join(path,'Datasets/CAISO/caiso_dict.pkl.pgz'), 'wb') as f:
            pickle.dump(sd,f)

In [24]:
with pgzip.open(os.path.join(path,'Datasets/CAISO/caiso_dict.pkl.pgz')) as f:
            sd = pickle.load(f)

In [25]:
sd

{'start_time': datetime.datetime(2018, 12, 31, 0, 0, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200))),
 'tensor': tensor([21953.1462, 21203.7162, 20620.2685,  ..., 33489.8885, 31292.4785,
         28781.0817], dtype=torch.float64)}

In [26]:
len(sd['tensor'])

56951

In [27]:
type(sd['tensor'])

torch.Tensor

In [28]:
torch.stack([sd['tensor']]).unsqueeze(-1)

tensor([[[21953.1462],
         [21203.7162],
         [20620.2685],
         ...,
         [33489.8885],
         [31292.4785],
         [28781.0817]]], dtype=torch.float64)

In [29]:
start_idx = 0
end_idx = 9999999
seq_len = 816
pred_horz = 24
stride=-1
timestamp = True

with pgzip.open(os.path.join(path,'Datasets/CAISO/caiso_dict.pkl.pgz')) as f:
            sd = pickle.load(f)

In [30]:
series = sd["tensor"] #121296 total elements
starttime = sd['start_time']
        
total_datapoints = len(series)
        
end_idx = min(end_idx,len(series))

In [31]:
series

tensor([21953.1462, 21203.7162, 20620.2685,  ..., 33489.8885, 31292.4785,
        28781.0817], dtype=torch.float64)

In [32]:
starttime + -13046 *datetime.timedelta(hours=1)

datetime.datetime(2017, 7, 5, 10, 0, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200)))

In [33]:
attr_dset_smpl_rt = 24 #Samples per day. Spain, AEP: 24, London: 48 
param_dset_lookback_weeks = 5
param_dset_forecast = 48

param_dset_lookback = param_dset_lookback_weeks*7*attr_dset_smpl_rt - param_dset_forecast

seq_len = param_dset_lookback
pred_horz = param_dset_forecast

In [34]:
seq_len

792

In [35]:
pred_horz

48

In [36]:
path = os.getcwd()

In [37]:
from Datasets.CAISO.caiso_def import CAISO
full_set = CAISO(path = os.path.join(path + "/Datasets/CAISO"),
                      seq_len = param_dset_lookback,
                      pred_horz = param_dset_forecast,
                      timestamp = False)
dytmax = full_set.max()
dytmin = full_set.min()
del(full_set)
    
train_set = CAISO(path = os.path.join(path + "/Datasets/CAISO"),
                    start_idx = 0, end_idx = 18983,
                    seq_len = param_dset_lookback,
                    pred_horz = param_dset_forecast,
                    timestamp = False)
val_set = CAISO(path = os.path.join(path + "/Datasets/CAISO"),
                  start_idx = 18983, end_idx = 2*18983,
                    seq_len = param_dset_lookback,
                    pred_horz = param_dset_forecast,
                    timestamp = False)
test_set = CAISO(path = os.path.join(path + "/Datasets/CAISO"),
                    start_idx = 2*18983,
                    seq_len = param_dset_lookback,
                    pred_horz = param_dset_forecast,
                    timestamp = False)
    
train_set.series = (train_set.series.half() - dytmin)/(dytmax - dytmin)
val_set.series = (val_set.series.half() - dytmin)/(dytmax - dytmin)
test_set.series = (test_set.series.half() - dytmin)/(dytmax - dytmin)

In [38]:
#Transformer only parameters
param_trf_edim = 24
param_trf_heads = 4
param_trf_elyr = 4
param_trf_dlyr = 4
param_trf_ffdim = 256
param_trf_weather = False

#Bigbird only parameters
param_trf_bksz = 48

#Training Params
arg_ini_lr = 1e-4
arg_batchsz = 'auto'
arg_epochs = 1000

custom_collate = torch.utils.data.default_collate

In [39]:
train_loader = torch.utils.data.DataLoader(train_set,batch_size=32,
                                           shuffle=True, collate_fn= custom_collate,
                                           pin_memory=True)

In [40]:
train_loader

In [41]:
train_loader.dataset.series

tensor([[[0.1956],
         [0.1750],
         [0.1593],
         ...,
         [0.3137],
         [0.2634],
         [0.2203]],

        [[0.1929],
         [0.1746],
         [0.1642],
         ...,
         [0.3088],
         [0.2593],
         [0.2191]],

        [[0.1934],
         [0.1694],
         [0.1523],
         ...,
         [0.2961],
         [0.2430],
         [0.1942]],

        ...,

        [[0.1262],
         [0.1162],
         [0.1122],
         ...,
         [0.3132],
         [0.2644],
         [0.2213]],

        [[0.1959],
         [0.1772],
         [0.1689],
         ...,
         [0.2783],
         [0.2378],
         [0.2000]],

        [[0.1755],
         [0.1572],
         [0.1459],
         ...,
         [0.2632],
         [0.2278],
         [0.1912]]], dtype=torch.float16)

In [42]:
scaler = torch.cuda.amp.GradScaler()

/var/tmp/pbs.4905179.sawtoothpbs/ipykernel_72959/2340218076.py:1: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()

In [43]:
import sys
sys.path.append("./Models")
import os
os.system('')

0

In [44]:
from Models.tsrnn import TSRNN, DPTrainableTSRNN
from Models.BigBirdSparse.SparseTransformerBB import TransformerBBSparse, TransformerBBFixed
from Models.transformer_base import Transformer_Base, DPTrainable

In [45]:
cuda_lead = torch.device("cuda:0")

In [46]:

model = TSRNN(smpl_rate = attr_dset_smpl_rt,
                  pred_horz = param_dset_forecast,
                  num_weeks = param_dset_lookback_weeks)
dpm = DPTrainableTSRNN(model,cuda_devices=None)
model.to(cuda_lead)

TSRNN(
  (full_rnn_layers): ModuleList(
    (0): Eidetic_LSTM(
      (inp_conv): Conv3d(1, 448, kernel_size=(3, 3, 2), stride=(1, 1, 1), padding=same)
      (hid_conv): Conv3d(64, 256, kernel_size=(3, 3, 2), stride=(1, 1, 1), padding=same)
      (gmem_conv): Conv3d(64, 256, kernel_size=(3, 3, 2), stride=(1, 1, 1), padding=same)
      (out_cell_conv): Conv3d(64, 64, kernel_size=(3, 3, 2), stride=(1, 1, 1), padding=same)
      (out_gmem_conv): Conv3d(64, 64, kernel_size=(3, 3, 2), stride=(1, 1, 1), padding=same)
      (out_memory_conv): Conv3d(128, 64, kernel_size=(1, 1, 1), stride=(1, 1, 1), padding=same)
      (hid_norm): LayerNorm((256, 2, 13, 24), eps=1e-05, elementwise_affine=True)
      (inp_norm): LayerNorm((448, 2, 13, 24), eps=1e-05, elementwise_affine=True)
      (cell_norm): LayerNorm((64, 2, 13, 24), eps=1e-05, elementwise_affine=True)
      (gmem_norm): LayerNorm((256, 2, 13, 24), eps=1e-05, elementwise_affine=True)
    )
    (1): Eidetic_LSTM(
      (inp_conv): Conv3d(64, 448, kernel_size=(3, 3, 2), stride=(1, 1, 1), padding=same)
      (hid_conv): Conv3d(64, 256, kernel_size=(3, 3, 2), stride=(1, 1, 1), padding=same)
      (gmem_conv): Conv3d(64, 256, kernel_size=(3, 3, 2), stride=(1, 1, 1), padding=same)
      (out_cell_conv): Conv3d(64, 64, kernel_size=(3, 3, 2), stride=(1, 1, 1), padding=same)
      (out_gmem_conv): Conv3d(64, 64, kernel_size=(3, 3, 2), stride=(1, 1, 1), padding=same)
      (out_memory_conv): Conv3d(128, 64, kernel_size=(1, 1, 1), stride=(1, 1, 1), padding=same)
      (hid_norm): LayerNorm((256, 2, 13, 24), eps=1e-05, elementwise_affine=True)
      (inp_norm): LayerNorm((448, 2, 13, 24), eps=1e-05, elementwise_affine=True)
      (cell_norm): LayerNorm((64, 2, 13, 24), eps=1e-05, elementwise_affine=True)
      (gmem_norm): LayerNorm((256, 2, 13, 24), eps=1e-05, elementwise_affine=True)
    )
  )
  (main_rnn_out_conv): Conv3d(64, 1, kernel_size=(2, 1, 1), stride=(2, 1, 1))
)

In [47]:
opt = torch.optim.AdamW(model.parameters(),lr = arg_ini_lr)

In [48]:
l,ls = dpm.train_epoch(train_loader, opt, device = cuda_lead, scaler = scaler)

/home/lambpc/AMARANTH/opensourcegridmodeling/Transformer/code/code/Models/tsrnn.py:312: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(dtype = torch.bfloat16):
/home/lambpc/.conda/envs/AustinTXForecast/lib/python3.13/site-packages/torch/nn/modules/conv.py:712: UserWarning: Using padding='same' with even kernel lengths and odd dilation may require a zero-padded copy of the input be created (Triggered internally at /pytorch/aten/src/ATen/native/Convolution.cpp:1027.)
  return F.conv3d(
/home/lambpc/.conda/envs/AustinTXForecast/lib/python3.13/site-packages/torch/nn/parallel/_functions.py:71: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn(
/home/lambpc/.conda/envs/AustinTXForecast/lib/python3.13/site-packages/numpy/_core/_methods.py:222: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/lambpc/.conda/envs/AustinTXForecast/lib/python3.13/site-packages/numpy/_core/_methods.py:214: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

In [49]:
dir(train_loader)

['_DataLoader__initialized',
 '_DataLoader__multiprocessing_context',
 '_IterableDataset_len_called',
 '__annotations__',
 '__class__',
 '__class_getitem__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__firstlineno__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__orig_bases__',
 '__parameters__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__static_attributes__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_auto_collation',
 '_dataset_kind',
 '_get_iterator',
 '_index_sampler',
 '_iterator',
 'batch_sampler',
 'batch_size',
 'check_worker_number_rationality',
 'collate_fn',
 'dataset',
 'drop_last',
 'generator',
 'in_order',
 'multiprocessing_context',
 'num_workers',
 'persistent_workers',
 'pin_memory',
 'pin_memory_device',
 'prefetch_factor',
 'sampler',
 'timeout',
 'worker_init_fn']

In [55]:
val_loader = torch.utils.data.DataLoader(val_set,batch_size=32, collate_fn = custom_collate)
test_loader = torch.utils.data.DataLoader(test_set,batch_size=32, collate_fn = custom_collate)

In [57]:
import time
import copy
scaler = torch.cuda.amp.GradScaler()


best_model_state = None
best_val = 999999

epoch_start = 0
epoch_end = 0
avg_epoch_dur = 0
for i in range(arg_epochs):
    epoch_start = time.time_ns()
    
    l,ls = dpm.train_epoch(train_loader, opt, device = cuda_lead, scaler = scaler)    
    vl,vls = dpm.val(val_loader,
                     loss_fn = lambda x,y: torch.nn.MSELoss(reduction='none')(x, y).\
                             nanmean(dim=-2).\
                             sqrt_(),
                    device = cuda_lead)
    
    epoch_end = time.time_ns()
    vl_improved = (vl < best_val)
    if vl_improved:
        best_val = vl
        best_model_state = copy.deepcopy(model.state_dict())

    print("                                                  ",end="\r")
    if vl_improved:
        print("Epoch {0}: loss = {1}, val_loss =\033[1;32m {2} \033[1;37m".format(i,l,vl))
    else:
        print("Epoch {0}: loss = {1}, val_loss = {2}".format(i,l,vl))
    
    #Estimate completion time
    epoch_dur_sec = (epoch_end-epoch_start)/(1000000000)
    if i == 0:
        avg_epoch_dur = epoch_dur_sec
    avg_epoch_dur = 0.3*epoch_dur_sec + 0.7*avg_epoch_dur
    etc_sec = (arg_epochs - i - 1)*avg_epoch_dur
    est_hrs = int(etc_sec//3600)
    est_mins = round((etc_sec%3600)/60)
    if est_mins == 60:
        est_mins = 0
        est_hrs += 1
    print("Estimated time to complete: {0}h {1}m".format(est_hrs,est_mins),end='\r')

final_model_state = model.state_dict()
for key in final_model_state:
    final_model_state[key] = final_model_state[key].cpu().detach().numpy()

best_model_dpt = copy.deepcopy(dpm)
best_model_dpt.module.load_state_dict(best_model_state)


torch.cuda.empty_cache()
# def vis(model,dataset,device,idx=0):
#     model.eval()
#     (vis_src_, vis_tar_)  = dataset.__getitem__(idx)

#     src = vis_src_.detach().clone()
#     src = src.nan_to_num(0)
#     src = src.unsqueeze(0)

#     src = src.to(device)
#     out = model(src)
#     out_ = (dataset.max() - dataset.min())*out + dataset.min()
    
#     out_c = out_.cpu().detach()   

#     data = torch.cat((vis_src_,vis_tar_),dim=0)
#     data = (dataset.max() - dataset.min())*data + dataset.min()
#     disp_len1 = 336
#     plt.figure(dpi=400)
#     plt.plot(data[-disp_len1:],linewidth=0.5)
#     plt.plot(np.arange(disp_len1-48,disp_len1,1),out_c[0],linewidth=0.5)

#vis(best_model,test_set,torch.device("cuda:0"),idx=39)
    # disp_len2 = 336
    # plt.figure(dpi=240)
    # plt.plot(data[-disp_len2:],linewidth=0.5)
    # plt.plot(np.arange(disp_len2-24,disp_len2,1),out_c[0],linewidth=0.5)
losses = [ lambda x,y: torch.nn.MSELoss(reduction='none')(x, y).\
                          nanmean(dim=-2),
           lambda x,y: torch.nn.MSELoss(reduction='none')(x, y).\
                                     nanmean(dim=-2).sqrt_(),
           lambda x,t: (x-t).abs_().nanmean(dim=-2),
           lambda x,t: (2*(t-x).abs_() / (t.abs() + x.abs())).nanmean(dim=-2)]

test_loss , tls = dpm.val(test_loader,
                          loss_fn = losses,
                          device = cuda_lead)
print("Test loss (Final Epoch): {0}".format(test_loss))
test_loss , tls = best_model_dpt.val(test_loader,
                          loss_fn = losses,
                          device = cuda_lead)
print("Test loss (Best Validation): {0}".format(test_loss))

/var/tmp/pbs.4905179.sawtoothpbs/ipykernel_72959/3131824892.py:3: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()

Epoch 0: loss = 0.08469369262456894, val_loss = 0.15933562815189362
Epoch 1: loss = 0.1107635647058487, val_loss = 0.08553681522607803
Epoch 2: loss = 0.070893794298172, val_loss = 0.08045203238725662
Epoch 3: loss = 0.047464899718761444, val_loss = 0.12078707665205002
Epoch 4: loss = 0.053828924894332886, val_loss = 0.12258543819189072
Epoch 5: loss = 0.05930565297603607, val_loss = 0.09107670187950134
Epoch 6: loss = 0.04858207702636719, val_loss = 0.06720919907093048
Epoch 7: loss = 0.040037017315626144, val_loss = 0.07361084222793579
Epoch 8: loss = 0.03861689195036888, val_loss = 0.08030939847230911
Epoch 9: loss = 0.03831678256392479, val_loss = 0.06977880001068115
Epoch 10: loss = 0.03351122885942459, val_loss = 0.06015157327055931
Epoch 11: loss = 0.02922239899635315, val_loss = 0.07003159075975418
Epoch 12: loss = 0.027103617787361145, val_loss = 0.0867639109492302
Epoch 13: loss = 0.030239850282669067, val_loss = 0.09347529709339142
Epoch 14: loss = 0.03191831335425377, val_loss = 0.0884333923459053
Epoch 15: loss = 0.030000824481248856, val_loss = 0.07419608533382416
Epoch 16: loss = 0.026786204427480698, val_loss = 0.06316196173429489
Epoch 17: loss = 0.025816088542342186, val_loss = 0.058426059782505035
Epoch 18: loss = 0.024601057171821594, val_loss = 0.061568573117256165
Epoch 19: loss = 0.024101827293634415, val_loss = 0.06219010055065155
Epoch 20: loss = 0.023766234517097473, val_loss = 0.06163529306650162
Epoch 21: loss = 0.02267010137438774, val_loss = 0.06267575174570084
Epoch 22: loss = 0.022693198174238205, val_loss = 0.06418053805828094
Epoch 23: loss = 0.02285725064575672, val_loss = 0.06380575150251389
Epoch 24: loss = 0.021325409412384033, val_loss = 0.06018613278865814
Epoch 25: loss = 0.020767338573932648, val_loss = 0.05691954866051674
Epoch 26: loss = 0.019859831780195236, val_loss = 0.05580741539597511
Epoch 27: loss = 0.019239023327827454, val_loss = 0.05541429668664932
Epoch 28: loss = 0.01970457285642624, val_loss = 0.055943846702575684
Epoch 29: loss = 0.019244462251663208, val_loss = 0.05696997791528702
Epoch 30: loss = 0.018928049132227898, val_loss = 0.06203131377696991
Epoch 31: loss = 0.01888381689786911, val_loss = 0.06408637017011642
Epoch 32: loss = 0.018388016149401665, val_loss = 0.06421733647584915
Epoch 33: loss = 0.01730981469154358, val_loss = 0.06036657094955444
Epoch 34: loss = 0.01702502742409706, val_loss = 0.058664534240961075
Epoch 35: loss = 0.015946906059980392, val_loss = 0.05665946006774902
Epoch 36: loss = 0.01622040942311287, val_loss = 0.05772562325000763
Epoch 37: loss = 0.015881340950727463, val_loss = 0.05833880975842476
Epoch 38: loss = 0.01622334122657776, val_loss = 0.05873013660311699
Epoch 39: loss = 0.01566627249121666, val_loss = 0.06213878095149994
Epoch 40: loss = 0.015077955089509487, val_loss = 0.060823675245046616
Epoch 41: loss = 0.015053730458021164, val_loss = 0.059818923473358154
Epoch 42: loss = 0.0151200070977211, val_loss = 0.058646515011787415
Epoch 43: loss = 0.01450723223388195, val_loss = 0.05563749000430107
Epoch 44: loss = 0.014059029519557953, val_loss = 0.05593152344226837
Epoch 45: loss = 0.013569450937211514, val_loss = 0.05723114311695099
Epoch 46: loss = 0.01310873031616211, val_loss = 0.05747707188129425
Epoch 47: loss = 0.013269944116473198, val_loss = 0.05857803672552109
Epoch 48: loss = 0.012876537628471851, val_loss = 0.05933258682489395
Epoch 49: loss = 0.013280184008181095, val_loss = 0.05833621323108673
Epoch 50: loss = 0.012596486136317253, val_loss = 0.056586623191833496
Epoch 51: loss = 0.012158455327153206, val_loss = 0.05895164981484413
Epoch 52: loss = 0.01172371581196785, val_loss = 0.060021158307790756
Epoch 53: loss = 0.011467643082141876, val_loss = 0.05909789726138115
Epoch 54: loss = 0.011187398806214333, val_loss = 0.060300763696432114
Epoch 55: loss = 0.011158760637044907, val_loss = 0.05900608375668526
Epoch 56: loss = 0.01073857955634594, val_loss = 0.05750728026032448
Epoch 57: loss = 0.010957546532154083, val_loss = 0.05794266238808632
Epoch 58: loss = 0.010387157090008259, val_loss = 0.05864456668496132
Epoch 59: loss = 0.010747741907835007, val_loss = 0.057358209043741226
Epoch 60: loss = 0.010378045029938221, val_loss = 0.055925335735082626
Epoch 61: loss = 0.010175425559282303, val_loss = 0.055321093648672104
Epoch 62: loss = 0.009619856253266335, val_loss = 0.05493004620075226
Epoch 63: loss = 0.009426316246390343, val_loss = 0.056968748569488525
Epoch 64: loss = 0.009219230152666569, val_loss = 0.056555986404418945
Epoch 65: loss = 0.009029787965118885, val_loss = 0.05702966824173927
Epoch 66: loss = 0.009002206847071648, val_loss = 0.05484818294644356
Epoch 67: loss = 0.008859032765030861, val_loss = 0.05759606137871742
Epoch 68: loss = 0.008932529017329216, val_loss = 0.058023497462272644
Epoch 69: loss = 0.008841115981340408, val_loss = 0.059007689356803894
Epoch 70: loss = 0.008511850610375404, val_loss = 0.05510174110531807
Epoch 71: loss = 0.008669720031321049, val_loss = 0.05442409589886665
Epoch 72: loss = 0.008340544067323208, val_loss = 0.054483477026224136
Epoch 73: loss = 0.008825225755572319, val_loss = 0.056629084050655365
Epoch 74: loss = 0.008322013542056084, val_loss = 0.05760832875967026
Epoch 75: loss = 0.00819514598697424, val_loss = 0.055471375584602356
Epoch 76: loss = 0.008143705315887928, val_loss = 0.05427246168255806
Epoch 77: loss = 0.0073873563669621944, val_loss = 0.05603758990764618
Epoch 78: loss = 0.007707324810326099, val_loss = 0.05372991785407066
Epoch 79: loss = 0.007935999892652035, val_loss = 0.05638304725289345
Epoch 80: loss = 0.007593948394060135, val_loss = 0.05215870216488838
Epoch 81: loss = 0.007616203278303146, val_loss = 0.05735069140791893
Epoch 82: loss = 0.007565604988485575, val_loss = 0.05516261234879494
Epoch 83: loss = 0.007967707701027393, val_loss = 0.05441940948367119
Epoch 84: loss = 0.007257115561515093, val_loss = 0.05227255821228027
Epoch 85: loss = 0.006790231913328171, val_loss = 0.05384165048599243
Epoch 86: loss = 0.00698457844555378, val_loss = 0.058995164930820465
Epoch 87: loss = 0.006509355269372463, val_loss = 0.05469563975930214
Epoch 88: loss = 0.007097529713064432, val_loss = 0.05236775055527687
Epoch 89: loss = 0.00665362598374486, val_loss = 0.05239233747124672
Epoch 90: loss = 0.0064425598829984665, val_loss = 0.05379340425133705
Epoch 91: loss = 0.006633455865085125, val_loss = 0.05536160618066788
Epoch 92: loss = 0.006972073577344418, val_loss = 0.05293842777609825
Epoch 93: loss = 0.006609145551919937, val_loss = 0.05524545907974243
Epoch 94: loss = 0.006513489410281181, val_loss = 0.05847867950797081
Epoch 95: loss = 0.006320083048194647, val_loss = 0.05490487441420555
Epoch 96: loss = 0.006263078190386295, val_loss = 0.05204186588525772
Epoch 97: loss = 0.006116297096014023, val_loss = 0.05550554767251015
Epoch 98: loss = 0.005763400346040726, val_loss = 0.05451616272330284
Epoch 99: loss = 0.006004695780575275, val_loss = 0.053306687623262405
Epoch 100: loss = 0.006103083491325378, val_loss = 0.0541861392557621
Epoch 101: loss = 0.005710816942155361, val_loss = 0.05402832850813866
Epoch 102: loss = 0.005454700440168381, val_loss = 0.05584359169006348
Epoch 103: loss = 0.006164289079606533, val_loss = 0.0546133890748024
Epoch 104: loss = 0.0056069944985210896, val_loss = 0.057582661509513855
Epoch 105: loss = 0.005849526263773441, val_loss = 0.057494763284921646
Epoch 106: loss = 0.005185618530958891, val_loss = 0.05504937469959259
Epoch 107: loss = 0.00525747099891305, val_loss = 0.05390361696481705
Epoch 108: loss = 0.005622518714517355, val_loss = 0.050304219126701355
Epoch 109: loss = 0.00518428348004818, val_loss = 0.05164071172475815
Epoch 110: loss = 0.005105263087898493, val_loss = 0.054003164172172546
Epoch 111: loss = 0.005387476645410061, val_loss = 0.052591610699892044
Epoch 112: loss = 0.00504679000005126, val_loss = 0.0552353598177433
Epoch 113: loss = 0.005265515763312578, val_loss = 0.05717968940734863
Epoch 114: loss = 0.005164776928722858, val_loss = 0.05672215297818184
Epoch 115: loss = 0.0054904259741306305, val_loss = 0.0538485161960125
Epoch 116: loss = 0.004938972182571888, val_loss = 0.053713537752628326
Epoch 117: loss = 0.004926793277263641, val_loss = 0.05455358326435089
Epoch 118: loss = 0.004778997506946325, val_loss = 0.05549081787467003
Epoch 119: loss = 0.004696299321949482, val_loss = 0.05312352254986763
Epoch 120: loss = 0.004542598966509104, val_loss = 0.05548764765262604
Epoch 121: loss = 0.005050866398960352, val_loss = 0.05401481315493584
Epoch 122: loss = 0.004700395744293928, val_loss = 0.05435706302523613
Epoch 123: loss = 0.004542684182524681, val_loss = 0.058151256293058395
Epoch 124: loss = 0.004716596100479364, val_loss = 0.057585909962654114
Epoch 125: loss = 0.004789025988429785, val_loss = 0.05288431793451309
Epoch 126: loss = 0.004843917675316334, val_loss = 0.05516595020890236
Epoch 127: loss = 0.004635965451598167, val_loss = 0.06072830781340599
Epoch 128: loss = 0.004874854814261198, val_loss = 0.05312225595116615
Epoch 129: loss = 0.00450732558965683, val_loss = 0.05332323536276817
Epoch 130: loss = 0.004266996402293444, val_loss = 0.05983932316303253
Epoch 131: loss = 0.0052231689915061, val_loss = 0.052994098514318466
Epoch 132: loss = 0.004697961732745171, val_loss = 0.050605569034814835
Epoch 133: loss = 0.004631450865417719, val_loss = 0.06099153682589531
Epoch 134: loss = 0.0051054516807198524, val_loss = 0.052113596349954605
Epoch 135: loss = 0.004158281721174717, val_loss = 0.05231768265366554
Epoch 136: loss = 0.004511578008532524, val_loss = 0.05796274170279503
Epoch 137: loss = 0.00403037341311574, val_loss = 0.058615222573280334
Epoch 138: loss = 0.004485622514039278, val_loss = 0.05366797372698784
Epoch 139: loss = 0.004995460622012615, val_loss = 0.05649808421730995
Epoch 140: loss = 0.004096298478543758, val_loss = 0.0631021186709404
Epoch 141: loss = 0.004710722714662552, val_loss = 0.051856741309165955
Epoch 142: loss = 0.004767507780343294, val_loss = 0.050888024270534515
Epoch 143: loss = 0.003979536704719067, val_loss = 0.05984292924404144
Epoch 144: loss = 0.004886568523943424, val_loss = 0.05278607830405235
Epoch 145: loss = 0.003947264514863491, val_loss = 0.053766731172800064
Epoch 146: loss = 0.004243005067110062, val_loss = 0.059140074998140335
Epoch 147: loss = 0.003794141113758087, val_loss = 0.05732113495469093
Epoch 148: loss = 0.003926707431674004, val_loss = 0.05065571889281273
Epoch 149: loss = 0.0037582344375550747, val_loss = 0.05063386261463165
Epoch 150: loss = 0.0040895468555390835, val_loss = 0.05526057630777359
Epoch 151: loss = 0.00404818682000041, val_loss = 0.050715282559394836
Epoch 152: loss = 0.0036512790247797966, val_loss = 0.05207878723740578
Epoch 153: loss = 0.004284583032131195, val_loss = 0.058601584285497665
Epoch 154: loss = 0.003696730826050043, val_loss = 0.05649556964635849
Epoch 155: loss = 0.0034981356002390385, val_loss = 0.04967181384563446
Epoch 156: loss = 0.004107081796973944, val_loss = 0.05768020451068878
Epoch 157: loss = 0.0035733631812036037, val_loss = 0.057378172874450684
Epoch 158: loss = 0.003917675465345383, val_loss = 0.05145174264907837
Epoch 159: loss = 0.003877977840602398, val_loss = 0.05455052852630615
Epoch 160: loss = 0.003709877375513315, val_loss = 0.05427040904760361
Epoch 161: loss = 0.003455599071457982, val_loss = 0.05343125760555267
Epoch 162: loss = 0.0036881347186863422, val_loss = 0.053736362606287
Epoch 163: loss = 0.0034346876200288534, val_loss = 0.055838584899902344
Epoch 164: loss = 0.0032906506676226854, val_loss = 0.05344574525952339
Epoch 165: loss = 0.0035658085253089666, val_loss = 0.05169660970568657
Epoch 166: loss = 0.003364675212651491, val_loss = 0.056413546204566956
Epoch 167: loss = 0.003349795239046216, val_loss = 0.05260355770587921
Epoch 168: loss = 0.0032357261516153812, val_loss = 0.05397585779428482
Epoch 169: loss = 0.0034795161336660385, val_loss = 0.05566376447677612
Epoch 170: loss = 0.0033347983844578266, val_loss = 0.057000115513801575
Epoch 171: loss = 0.0032458296045660973, val_loss = 0.0530240498483181
Epoch 172: loss = 0.0035395422019064426, val_loss = 0.054597701877355576
Epoch 173: loss = 0.0031878999434411526, val_loss = 0.057756517082452774
Epoch 174: loss = 0.003352194558829069, val_loss = 0.053482603281736374
Epoch 175: loss = 0.003431736258789897, val_loss = 0.0553974024951458
Epoch 176: loss = 0.003127438947558403, val_loss = 0.05952010303735733
Epoch 177: loss = 0.0035027689300477505, val_loss = 0.05473831668496132
Epoch 178: loss = 0.0033430990297347307, val_loss = 0.05669966712594032
Epoch 179: loss = 0.0030576784629374743, val_loss = 0.05732331424951553
Epoch 180: loss = 0.0031237052753567696, val_loss = 0.05307863652706146
Epoch 181: loss = 0.003063102485612035, val_loss = 0.05479021370410919
Epoch 182: loss = 0.0029404344968497753, val_loss = 0.05878326669335365
Epoch 183: loss = 0.0032796720042824745, val_loss = 0.05163578689098358
Epoch 184: loss = 0.0031702392734587193, val_loss = 0.05606095492839813
Epoch 185: loss = 0.002794254571199417, val_loss = 0.057287443429231644
Epoch 186: loss = 0.0030455340165644884, val_loss = 0.05287185683846474
Epoch 187: loss = 0.0031597577035427094, val_loss = 0.05563473701477051
Epoch 188: loss = 0.0026266027707606554, val_loss = 0.05645449459552765
Epoch 189: loss = 0.0027808193117380142, val_loss = 0.05407625064253807
Epoch 190: loss = 0.0027312980964779854, val_loss = 0.05456744506955147
Epoch 191: loss = 0.002868347568437457, val_loss = 0.06082050874829292
Epoch 192: loss = 0.002826390787959099, val_loss = 0.054719697684049606
Epoch 193: loss = 0.002770220162346959, val_loss = 0.05569375678896904
Epoch 194: loss = 0.0026224420871585608, val_loss = 0.05713486671447754
Epoch 195: loss = 0.0028108968399465084, val_loss = 0.05521243438124657
Epoch 196: loss = 0.002707695821300149, val_loss = 0.06065654754638672
Epoch 197: loss = 0.002781104063615203, val_loss = 0.05556296929717064
Epoch 198: loss = 0.0025302725844085217, val_loss = 0.05608619749546051
Epoch 199: loss = 0.0027618352323770523, val_loss = 0.05993454158306122
Epoch 200: loss = 0.0027225022204220295, val_loss = 0.05208677425980568
Epoch 201: loss = 0.0029396777972579002, val_loss = 0.05753063037991524
Epoch 202: loss = 0.0025184089317917824, val_loss = 0.05775772035121918
Epoch 203: loss = 0.002546390751376748, val_loss = 0.05479775741696358
Epoch 204: loss = 0.0026186946779489517, val_loss = 0.05455498397350311
Epoch 205: loss = 0.0026110741309821606, val_loss = 0.058063432574272156
Epoch 206: loss = 0.00259990431368351, val_loss = 0.05673107132315636
Epoch 207: loss = 0.002372779417783022, val_loss = 0.05814628675580025
Epoch 208: loss = 0.0024017561227083206, val_loss = 0.05472060665488243
Epoch 209: loss = 0.0023810865823179483, val_loss = 0.05676667392253876
Epoch 210: loss = 0.0023807764519006014, val_loss = 0.0573418028652668
Epoch 211: loss = 0.002479112707078457, val_loss = 0.05327983200550079
Epoch 212: loss = 0.0025694251526147127, val_loss = 0.05824458599090576
Epoch 213: loss = 0.00232381047680974, val_loss = 0.05597382411360741
Epoch 214: loss = 0.0022504758089780807, val_loss = 0.05614683777093887
Epoch 215: loss = 0.00216376013122499, val_loss = 0.05775175243616104
Epoch 216: loss = 0.002238153014332056, val_loss = 0.056202229112386703
Epoch 217: loss = 0.002270643599331379, val_loss = 0.05483117327094078
Epoch 218: loss = 0.0022423870395869017, val_loss = 0.05931072309613228
Epoch 219: loss = 0.0024196256417781115, val_loss = 0.05350351333618164
Epoch 220: loss = 0.0024758833460509777, val_loss = 0.059389423578977585
Epoch 221: loss = 0.0022708706092089415, val_loss = 0.05404212698340416
Epoch 222: loss = 0.002182695781812072, val_loss = 0.056041911244392395
Epoch 223: loss = 0.002202829113230109, val_loss = 0.05874316394329071
Epoch 224: loss = 0.0022565710823982954, val_loss = 0.055754732340574265
Epoch 225: loss = 0.002369409194216132, val_loss = 0.061757978051900864
Epoch 226: loss = 0.0022429763339459896, val_loss = 0.059549711644649506
Epoch 227: loss = 0.0021373319905251265, val_loss = 0.05993109568953514
Epoch 228: loss = 0.0021917351987212896, val_loss = 0.05854460224509239
Epoch 229: loss = 0.0021108670625835657, val_loss = 0.05734008923172951
Epoch 230: loss = 0.002151910914108157, val_loss = 0.06006605923175812
Epoch 231: loss = 0.0020820533391088247, val_loss = 0.05840257182717323
Epoch 232: loss = 0.0020616522524505854, val_loss = 0.061157092452049255
Epoch 233: loss = 0.002127637853845954, val_loss = 0.05552227422595024
Epoch 234: loss = 0.00219274521805346, val_loss = 0.062315378338098526
Epoch 235: loss = 0.0022328821942210197, val_loss = 0.05763668194413185
Epoch 236: loss = 0.0020463706459850073, val_loss = 0.05639079958200455
Epoch 237: loss = 0.0020814253948628902, val_loss = 0.06694073230028152
Epoch 238: loss = 0.0026440941728651524, val_loss = 0.0561586357653141
Epoch 239: loss = 0.0029794229194521904, val_loss = 0.06566913425922394
Epoch 240: loss = 0.0024113296531140804, val_loss = 0.05829969793558121
Epoch 241: loss = 0.002018458442762494, val_loss = 0.054333869367837906
Epoch 242: loss = 0.0022450070828199387, val_loss = 0.06457871198654175
Epoch 243: loss = 0.0024649370461702347, val_loss = 0.05413025990128517
Epoch 244: loss = 0.002217961475253105, val_loss = 0.05498987436294556
Epoch 245: loss = 0.0018849822226911783, val_loss = 0.06099909916520119
Epoch 246: loss = 0.002028808696195483, val_loss = 0.05489571392536163
Epoch 247: loss = 0.0018657593755051494, val_loss = 0.057338714599609375
Epoch 248: loss = 0.001904511358588934, val_loss = 0.06013605743646622
Epoch 249: loss = 0.0019551387522369623, val_loss = 0.05525653064250946
Epoch 250: loss = 0.0019841727335006, val_loss = 0.05716672167181969
Epoch 251: loss = 0.0019442405318841338, val_loss = 0.06244761124253273
Epoch 252: loss = 0.0022657837253063917, val_loss = 0.054704900830984116
Epoch 253: loss = 0.002481575356796384, val_loss = 0.05863924324512482
Epoch 254: loss = 0.001918165129609406, val_loss = 0.0596143938601017
Epoch 255: loss = 0.0018201434286311269, val_loss = 0.055357906967401505
Epoch 256: loss = 0.0021024448797106743, val_loss = 0.05866333469748497
Epoch 257: loss = 0.0017892858013510704, val_loss = 0.06108788400888443
Epoch 258: loss = 0.002039333339780569, val_loss = 0.05332588031888008
Epoch 259: loss = 0.0023177554830908775, val_loss = 0.0585646852850914
Epoch 260: loss = 0.0018207207322120667, val_loss = 0.06003107875585556
Epoch 261: loss = 0.00188537803478539, val_loss = 0.05519253388047218
Epoch 262: loss = 0.0022142447996884584, val_loss = 0.059016600251197815
Epoch 263: loss = 0.0018420491833239794, val_loss = 0.05908308923244476
Epoch 264: loss = 0.001746918074786663, val_loss = 0.05513693392276764
Epoch 265: loss = 0.0017889149021357298, val_loss = 0.058064814656972885
Epoch 266: loss = 0.0017593808006495237, val_loss = 0.058464691042900085
Epoch 267: loss = 0.0016269967891275883, val_loss = 0.056315477937459946
Epoch 268: loss = 0.0016862726770341396, val_loss = 0.0558481439948082
Epoch 269: loss = 0.0016922280192375183, val_loss = 0.058755163103342056
Epoch 270: loss = 0.0016490222187712789, val_loss = 0.05871623754501343
Epoch 271: loss = 0.0016338636633008718, val_loss = 0.05553925037384033
Epoch 272: loss = 0.001648851903155446, val_loss = 0.05837097391486168
Epoch 273: loss = 0.0016498904442414641, val_loss = 0.05739358440041542
Epoch 274: loss = 0.0016018579481169581, val_loss = 0.057145822793245316
Epoch 275: loss = 0.001603942597284913, val_loss = 0.05706135928630829
Epoch 276: loss = 0.001545797218568623, val_loss = 0.05777261406183243
Epoch 277: loss = 0.0015080823795869946, val_loss = 0.05822700634598732
Epoch 278: loss = 0.0015968026127666235, val_loss = 0.05808297544717789
Epoch 279: loss = 0.0015414401423186064, val_loss = 0.05853253975510597
Epoch 280: loss = 0.0015420694835484028, val_loss = 0.05425550788640976

In [64]:
def predict(loader: torch.utils.data.DataLoader, device):
    src_val = []
    tar_val = []
    out_val = []
    best_model_dpt.dpmod.eval()
            
    with torch.no_grad():
        for batch_idx, (src, tar) in enumerate(loader):
            src_ = src.to(device)
            tar_ = tar.to(device)
                
            src_ = src_.nan_to_num()
            out,_ = best_model_dpt.dpmod(src_)
                
            out_ = out #(25.695 - 9.581)*out + 9.581
                # loss = torch.nn.MSELoss(reduction='none')(out_, tar_).\
                #         nanmean(dim=-2).\
                #         sqrt_()

            src_val.append(src)
            tar_val.append(tar)
            out_val.append(out)
        
    return src_val, tar_val, out_val

In [181]:
import numpy as np
def predict_2(loader: torch.utils.data.DataLoader, device):
    src_val = []
    tar_val = []
    out_val = []
    
    best_model_dpt.dpmod.eval()

    with torch.no_grad():
        for batch_idx, (src,tar) in enumerate(loader):
            src_ = src.to(device)
            tar_ = tar.to(device)

            src_ = src_.nan_to_num()
            out,_ = best_model_dpt.dpmod(src_)
                
            out_ = out #(25.695 - 9.581)*out + 9.581
                # loss = torch.nn.MSELoss(reduction='none')(out_, tar_).\
                #         nanmean(dim=-2).\
                #         sqrt_()

                 # src_ is the predictions for input of src
                # tar_ is predictions for input of tar

                # To get the training preds for src, tar_val = src_

            for target in tar_:
                target = target.cpu()
                tar_val.append(target)

            for source in out_:
                source = source.cpu()
                src_val.append(source)

            for output in out_:
                output = output.cpu()
                out_val.append(output)

    
        tar_val = np.array(tar_val).flatten()
        src_val = np.array(src_val).flatten()
        out_val = np.array(out_val).flatten()
        
        return src_val, tar_val

In [182]:
src,tar = predict_2(train_loader, cuda_lead)

In [183]:
src.shape

(1056,)

In [184]:
tar.shape

(1056,)