# Preprocess data for Austin TX from 2002 to 2025

Copyright 2026, Battelle Energy Alliance, LLC, ALL RIGHTS RESERVED

In [1]:
import pandas as pd

In [2]:
full_data = pd.read_csv("4049454.csv")

/var/tmp/pbs.4501175.sawtoothpbs/ipykernel_79361/2605919208.py:1: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  full_data = pd.read_csv("4049454.csv")

In [3]:
full_data.head()

,STATION,DATE,REPORT_TYPE,SOURCE,HourlyDryBulbTemperature,HourlyPrecipitation,HourlyPresentWeatherType,HourlyRelativeHumidity,HourlyWindSpeed
0,USW00013958,1948-01-01T00:00:00,SAO,335.0,37.0,NaN,NaN,70.0,11.0
1,USW00013958,1948-01-01T00:00:00,SOD,NaN,NaN,NaN,NaN,NaN,NaN
2,USW00013958,1948-01-01T00:00:00,SOM,NaN,NaN,NaN,NaN,NaN,NaN
3,USW00013958,1948-01-01T01:00:00,SAO,335.0,36.0,NaN,NaN,62.0,26.0
4,USW00013958,1948-01-01T02:00:00,SAO,335.0,35.0,NaN,NaN,67.0,22.0

In [4]:
full_data.tail()

,STATION,DATE,REPORT_TYPE,SOURCE,HourlyDryBulbTemperature,HourlyPrecipitation,HourlyPresentWeatherType,HourlyRelativeHumidity,HourlyWindSpeed
743382,USW00013958,2025-05-01T21:51:00,FM-15,343.0,68.0,NaN,NaN,73.0,10.0
743383,USW00013958,2025-05-01T22:51:00,FM-15,343.0,66.0,NaN,NaN,75.0,7.0
743384,USW00013958,2025-05-01T23:51:00,FM-15,343.0,66.0,NaN,NaN,70.0,3.0
743385,USW00013958,2025-05-02T00:00:00,SOD,NaN,NaN,NaN,NaN,NaN,NaN
743386,USW00013958,2025-05-03T00:00:00,SOD,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
full_data['DATE'] = pd.to_datetime(full_data['DATE'])

get data for 2002 to 2017

In [16]:
data02to17 = full_data.loc[(full_data.DATE.dt.year >= 2002) & (full_data.DATE.dt.year <= 2017)]

In [17]:
data02to17.head()

,STATION,DATE,REPORT_TYPE,SOURCE,HourlyDryBulbTemperature,HourlyPrecipitation,HourlyPresentWeatherType,HourlyRelativeHumidity,HourlyWindSpeed
431142,USW00013958,2002-01-01 00:00:00,FM-12,220.0,36.0,NaN,NaN,NaN,6.0
431143,USW00013958,2002-01-01 00:00:00,SOD,NaN,NaN,NaN,NaN,NaN,NaN
431144,USW00013958,2002-01-01 00:00:00,SOM,NaN,NaN,NaN,NaN,NaN,NaN
431145,USW00013958,2002-01-01 00:51:00,FM-15,335.0,36.0,0.00,||00 00 00,64.0,7.0
431146,USW00013958,2002-01-01 01:51:00,FM-15,335.0,36.0,0.00,||00 00 00,57.0,8.0

In [18]:
data02to17.tail()

,STATION,DATE,REPORT_TYPE,SOURCE,HourlyDryBulbTemperature,HourlyPrecipitation,HourlyPresentWeatherType,HourlyRelativeHumidity,HourlyWindSpeed
644345,USW00013958,2017-12-31 22:30:00,FM-16,343.0,27.0,T,-SN:03 |SN |,81.0,10.0
644346,USW00013958,2017-12-31 22:51:00,FM-15,343.0,28.0,T,NaN,78.0,9.0
644347,USW00013958,2017-12-31 23:06:00,FM-16,343.0,28.0,NaN,NaN,81.0,10.0
644348,USW00013958,2017-12-31 23:26:00,FM-16,343.0,27.0,NaN,NaN,78.0,11.0
644349,USW00013958,2017-12-31 23:51:00,FM-15,343.0,27.0,0.00,NaN,78.0,6.0

In [19]:
data02to17.to_csv("ElectricityDemandAustinTX/LoadForecastingAttacks/Weather/weather_data_2002to2017.csv")